# Generated by Django 2.0.4 on 2018-05-27 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='编号')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('sell_choices', models.SmallIntegerField(choices=[(0, '默认'), (1, '买'), (2, '卖')], default=0, verbose_name='买卖方向')),
                ('remark', models.CharField(max_length=255, verbose_name='备注')),
                ('deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('stockcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stocks.Listing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StrategyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('orderid', models.SmallIntegerField(verbose_name='序号')),
                ('num', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='数量')),
                ('expressions', models.CharField(default='', max_length=255, verbose_name='表达式')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='strategies.Strategy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StrategyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='编号')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('remark', models.CharField(max_length=255, verbose_name='备注')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='strategy',
            name='strategytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='strategies.StrategyType'),
        ),
    ]
