# Generated by Django 2.0.4 on 2018-04-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
        migrations.AddField(
            model_name='strategydetail',
            name='expressions',
            field=models.CharField(default='', max_length=255, verbose_name='表达式'),
        ),
        migrations.AddField(
            model_name='strategydetail',
            name='num',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='数量'),
        ),
    ]
