# Generated by Django 2.0.2 on 2018-04-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wangges', '0006_auto_20180408_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zxg',
            name='code',
        ),
        migrations.DeleteModel(
            name='Stockcode',
        ),
        migrations.DeleteModel(
            name='ZXG',
        ),
    ]
