# Generated by Django 2.0.2 on 2018-04-12 11:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wangges', '0007_auto_20180412_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='代码')),
                ('name', models.CharField(max_length=8, verbose_name='名称')),
                ('usedName', models.CharField(default='', max_length=255, verbose_name='曾用名')),
                ('market', models.IntegerField(choices=[(0, '深市'), (1, '沪市')], default=0, verbose_name='市场')),
                ('update', models.DateField(verbose_name='上市日期')),
                ('isindex', models.SmallIntegerField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='是否指数')),
                ('isdelisted', models.SmallIntegerField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='是否退市')),
            ],
        ),
        migrations.CreateModel(
            name='ZXG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('remark', models.CharField(default='', max_length=250, verbose_name='备注')),
                ('isactived', models.BooleanField(choices=[(False, '否'), (True, '是')], verbose_name='有效')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wangges.Stockcode')),
            ],
        ),
    ]
