# Generated by Django 2.0.4 on 2018-04-21 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, unique=True, verbose_name='板块名称')),
                ('remark', models.CharField(default='', max_length=250, verbose_name='备注')),
                ('isactived', models.BooleanField(choices=[(False, '否'), (True, '是')], verbose_name='有效')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.BK', verbose_name='上级板块')),
            ],
        ),
        migrations.CreateModel(
            name='Stockcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='代码')),
                ('name', models.CharField(max_length=8, verbose_name='名称')),
                ('usedName', models.CharField(default='', max_length=255, verbose_name='曾用名')),
                ('market', models.IntegerField(choices=[(0, '深市'), (1, '沪市')], default=0, verbose_name='市场')),
                ('update', models.DateField(verbose_name='上市日期')),
                ('isindex', models.SmallIntegerField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='是否指数')),
                ('isdelisted', models.SmallIntegerField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='是否退市')),
            ],
        ),
        migrations.CreateModel(
            name='ZXG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(default='', max_length=250, verbose_name='备注')),
                ('isactived', models.BooleanField(choices=[(False, '否'), (True, '是')], verbose_name='有效')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('bkname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.BK')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.Stockcode')),
            ],
        ),
    ]
