# Generated by Django 2.0.6 on 2018-06-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('port', models.SmallIntegerField(verbose_name='端口号')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '代理',
            },
        ),
        migrations.AlterUniqueTogether(
            name='proxy',
            unique_together={('ip', 'port')},
        ),
    ]
