# Generated by Django 2.0.4 on 2018-05-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockdetail',
            name='isactived',
            field=models.BooleanField(choices=[(True, '是'), (False, '否')], default=True, verbose_name='有效'),
        ),
    ]
