# Generated by Django 2.0.4 on 2018-05-17 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rps',
            name='tradedate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='交易日期'),
        ),
        migrations.AlterField(
            model_name='rpsprepare',
            name='tradedate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='交易日期'),
        ),
    ]
