# Generated by Django 2.0.4 on 2018-05-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockcode',
            name='isindex',
        ),
        migrations.AddField(
            model_name='stockcode',
            name='category',
            field=models.SmallIntegerField(choices=[(10, '沪市'), (11, '深市'), (12, '指数'), (13, '分级基金'), (14, '债券'), (15, '逆回购')], default=10, verbose_name='交易类别'),
        ),
        migrations.AlterField(
            model_name='bk',
            name='isactived',
            field=models.BooleanField(choices=[(True, '是'), (False, '否')], verbose_name='有效'),
        ),
        migrations.AlterField(
            model_name='stockcode',
            name='isdelisted',
            field=models.SmallIntegerField(choices=[(True, '是'), (False, '否')], default=False, verbose_name='是否退市'),
        ),
        migrations.AlterField(
            model_name='zxg',
            name='isactived',
            field=models.BooleanField(choices=[(True, '是'), (False, '否')], verbose_name='有效'),
        ),
    ]
