# Generated by Django 2.0.4 on 2018-05-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20180518_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rps',
            name='tradedate',
            field=models.DateField(verbose_name='交易日期'),
        ),
        migrations.AlterField(
            model_name='rpsprepare',
            name='tradedate',
            field=models.DateField(verbose_name='交易日期'),
        ),
    ]
