# Generated by Django 2.0.4 on 2018-05-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20180503_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcode',
            name='category',
            field=models.SmallIntegerField(choices=[(10, '股票'), (11, '指数'), (12, '分级基金'), (13, '债券'), (14, '逆回购')], default=10, verbose_name='交易类别'),
        ),
    ]
