# Generated by Django 2.0.6 on 2018-06-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20180613_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rps',
            name='tradedate',
            field=models.DateField(db_index=True, verbose_name='交易日期'),
        ),
        migrations.AlterField(
            model_name='rpsprepare',
            name='tradedate',
            field=models.DateField(db_index=True, verbose_name='交易日期'),
        ),
    ]
