# Generated by Django 2.0.4 on 2018-05-12 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20180511_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rps120', models.DecimalField(decimal_places=3, max_digits=7, null=True, verbose_name='RPS120')),
                ('rps250', models.DecimalField(decimal_places=3, max_digits=7, null=True, verbose_name='RPS250')),
                ('bkname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.BK')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.Stockcode', verbose_name='代码')),
            ],
        ),
    ]
