# Generated by Django 2.0.4 on 2018-05-05 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20180503_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockcode',
            old_name='update',
            new_name='timeToMarket',
        ),
    ]
