# Generated by Django 2.0.4 on 2018-05-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_listing_isactived'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSGTCG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='代码')),
                ('close', models.DecimalField(decimal_places=3, max_digits=9, null=True, verbose_name='收盘价')),
                ('hvol', models.DecimalField(decimal_places=3, max_digits=9, null=True, verbose_name='持股数量')),
                ('hamount', models.DecimalField(decimal_places=3, max_digits=9, null=True, verbose_name='持股金额')),
                ('hpercent', models.DecimalField(decimal_places=3, max_digits=9, null=True, verbose_name='持股数量占A股百分比')),
            ],
        ),
    ]
