# Generated by Django 2.0.4 on 2018-05-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_rps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcode',
            name='name',
            field=models.CharField(max_length=8, verbose_name='公司简称'),
        ),
    ]
