# Generated by Django 2.0.4 on 2018-05-15 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20180513_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPSprepare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rps120', models.DecimalField(decimal_places=3, max_digits=7, null=True, verbose_name='RPS120')),
                ('rps250', models.DecimalField(decimal_places=3, max_digits=7, null=True, verbose_name='RPS250')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.Stockcode', verbose_name='代码')),
            ],
            options={
                'verbose_name': 'RPS',
            },
        ),
    ]
