# Generated by Django 2.0.4 on 2018-05-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_hsgtcg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsgtcg',
            name='hamount',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True, verbose_name='持股金额'),
        ),
        migrations.AlterField(
            model_name='hsgtcg',
            name='hpercent',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True, verbose_name='持股数量占A股百分比'),
        ),
        migrations.AlterField(
            model_name='hsgtcg',
            name='hvol',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True, verbose_name='持股数量'),
        ),
    ]
