# Generated by Django 2.0.6 on 2018-06-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20180616_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rps',
            name='rps120',
            field=models.DecimalField(db_index=True, decimal_places=3, max_digits=7, null=True, verbose_name='RPS120'),
        ),
        migrations.AlterField(
            model_name='rps',
            name='rps250',
            field=models.DecimalField(db_index=True, decimal_places=3, max_digits=7, null=True, verbose_name='RPS250'),
        ),
        migrations.AlterField(
            model_name='rpsprepare',
            name='rps120',
            field=models.DecimalField(db_index=True, decimal_places=3, max_digits=7, null=True, verbose_name='RPS120'),
        ),
        migrations.AlterField(
            model_name='rpsprepare',
            name='rps250',
            field=models.DecimalField(db_index=True, decimal_places=3, max_digits=7, null=True, verbose_name='RPS250'),
        ),
    ]
