# Generated by Django 2.0.4 on 2018-05-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_rpsprepare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcode',
            name='code',
            field=models.CharField(db_index=True, max_length=10, verbose_name='代码'),
        ),
    ]
