# Generated by Django 2.0.6 on 2018-06-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20180627_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpsprepare',
            name='rps120',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True, verbose_name='RPS120'),
        ),
        migrations.AlterField(
            model_name='rpsprepare',
            name='rps250',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True, verbose_name='RPS250'),
        ),
    ]
