# Generated by Django 2.0.4 on 2018-05-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_auto_20180515_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rpsprepare',
            options={'verbose_name': 'RPS准备'},
        ),
        migrations.AlterModelOptions(
            name='stockcode',
            options={'verbose_name': '证券列表'},
        ),
    ]
