# Generated by Django 2.0.4 on 2018-05-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_auto_20180530_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsgtcg',
            name='tradedate',
            field=models.DateField(null=True, verbose_name='日期'),
        ),
    ]
