# Generated by Django 2.0.4 on 2018-05-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_auto_20180530_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSGTCGHold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, null=True, verbose_name='代码')),
                ('tradedate', models.DateField(null=True, verbose_name='日期')),
            ],
        ),
    ]
