# Generated by Django 2.0.4 on 2018-05-16 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_auto_20180515_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpsprepare',
            name='tradedate',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 16, 15, 19, 43, 948857), verbose_name='交易日期'),
        ),
    ]
