# Generated by Django 2.0.6 on 2018-07-03 03:39

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_category_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '类别', 'verbose_name_plural': '类别'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='详细描述'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='stocks.Category', verbose_name='上级类别'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.Category', verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='代码'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='详细描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='product',
            name='priceAustria',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True, verbose_name='推荐价格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stocks',
            field=models.IntegerField(blank=True, default=0, verbose_name='是否交易'),
        ),
    ]
