# Generated by Django 2.0.4 on 2018-05-31 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_hsgtcghold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hsgtcghold',
            options={'verbose_name': '沪深港通持股列表'},
        ),
        migrations.AlterUniqueTogether(
            name='hsgtcghold',
            unique_together={('code', 'tradedate')},
        ),
    ]
