# Generated by Django 2.0.6 on 2018-07-10 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_auto_20180703_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreshHigh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high', models.DecimalField(decimal_places=3, max_digits=9, null=True, verbose_name='最高价')),
                ('low', models.DecimalField(decimal_places=3, max_digits=9, null=True, verbose_name='最低价')),
                ('htradedate', models.DateField(db_index=True, null=True, verbose_name='最高点日期')),
                ('ltradedate', models.DateField(db_index=True, null=True, verbose_name='最低点日期')),
                ('code', models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.PROTECT, to='stocks.Listing', verbose_name='代码')),
            ],
            options={
                'verbose_name': '创一年新高',
            },
        ),
        migrations.AlterUniqueTogether(
            name='freshhigh',
            unique_together={('code', 'htradedate')},
        ),
    ]
