# Generated by Django 2.0.4 on 2018-05-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_auto_20180516_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rps',
            options={'verbose_name': 'RPS'},
        ),
        migrations.AlterModelOptions(
            name='stockday',
            options={'verbose_name': '日数据'},
        ),
        migrations.AlterField(
            model_name='rps',
            name='tradedate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='交易日期'),
        ),
        migrations.AlterUniqueTogether(
            name='rps',
            unique_together={('code', 'tradedate')},
        ),
        migrations.AlterUniqueTogether(
            name='rpsprepare',
            unique_together={('code', 'tradedate')},
        ),
        migrations.AlterUniqueTogether(
            name='stockcode',
            unique_together={('code', 'market', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='stockday',
            unique_together={('code', 'tradedate')},
        ),
    ]
